### ISSUE TITLE
Wrong data for DE-BE in cases-rki-by-state.csv

### ISSUE THREAD

**Issue by mathiasflick** [jgehrcke/covid-19-germany-gae#233]
It looks like cases for DE-BE are not correct - they are in fact pretty much two times the values published by RKI; the sum_cases row is correct, which leads to a discrepancy if I compute the sum myself; delta is - not really surprisingly - approx. half of the DE-BE value ...
  
Thanks for your valuable work and greetings from Cologne

Mathias

**Comment by jgehrcke** [comment]
Thank you for reporting this!

Will double-check in a minute. Already got the hunch that I introduced this bug ~20 days ago as part of this change: https://github.com/jgehrcke/covid-19-germany-gae/issues/176#issuecomment-715299431

**Comment by jgehrcke** [comment]
Indeed, after https://github.com/jgehrcke/covid-19-germany-gae/pull/192 the `DE-BE` column in https://github.com/jgehrcke/covid-19-germany-gae/blob/b88432e55d0ac9162886e55bef12f65a81adff31/cases-rki-by-state.csv was based on the actual Berlin counties _plus_ the virtual one with AGS 11000, leading to precisely the accidental factor 2.  When working on https://github.com/jgehrcke/covid-19-germany-gae/pull/192 I implemented _a_ correction (`sum_cases` stayed correct), but not the correct correction. Again, big big thanks for double-checking, validating, _and reporting_. Tremendously valuable.

Fixed in https://github.com/jgehrcke/covid-19-germany-gae/pull/235. Please check again!

**Comment by mathiasflick** [comment]
Double checked it - works like a charm -> correct values for DE-BE now!

**Comment by jgehrcke** [comment]
Thanks for reporting back! Much appreciated.
