### ISSUE TITLE
for the record: useful source for Landkreis metadata

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/covid-19-germany-gae#46]
NPGEO Corona
https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0
RKI Corona Landkreise
Last updated 14 hours ago | 412 Records

--
This is a great structured resource, describing the individual Landkreise with their metadata properties. The case count is _behind_, because this is the RKI view on case count.

But this LK metadata can be correlated with LK case count obtained by ZEIT ONLINE or https://github.com/corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping.
Screenshot:

![Screenshot from 2020-03-24 16-43-48](https://user-images.githubusercontent.com/265630/77446432-b1bfc300-6dee-11ea-80b9-ff886e46b7cf.png)

This table as CSV file: [here](https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0.csv)

**Comment by stefan123t** [comment]
Hi Jan-Philip,
wouldn't it be sufficient to just store a copy of the above CSV table per day, in order to compare with the various data provided by your various scraping scripts.
I think having a historical csv every day, would be sufficient for the short term. Maybe RKI / ESRI publish the missing data for past dates sometime in the future too.
Kind regards,
Stefan

IMHO running the following as a cronjob every day after 15:00 when RKI published their new numbers might already do the trick for that purpose:

/usr/bin/wget https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0.csv -o $(/bin/date +%F).csv

**Comment by jgehrcke** [comment]
Hey @stefan123t thanks for your thoughts! You are on the right track here I think. An important one in view of making sense of the case number data flow.

I have now found a method to automatically consume the RKI time series data with high spatial and temporal resolution, and the preliminary results are pretty insightful.

> Maybe RKI / ESRI publish the missing data for past dates sometime in the future too.

Yes, they absolutely do! The extent with which they add data _in hindsight_ is pretty astonishing, and it turns out that in terms of _looking at history_ there is only one credible data source: the RKI itself.

**Comment by jgehrcke** [comment]
Also see https://github.com/jgehrcke/covid-19-germany-gae/issues/58 CC @stefan123t

**Comment by jgehrcke** [comment]
Landkreis metadata now here, ready for consumption, especially for AGS lookup: https://github.com/jgehrcke/covid-19-germany-gae/blob/master/ags.json
