### ISSUE TITLE
Time Shift in Gehrcke VS RiskLayer

### ISSUE THREAD

**Issue by bdiv** [jgehrcke/covid-19-germany-gae#536]
Hello Dr. Gehrcke!
First I'd like to thank for for the aggregation you provide. Very helpful! :)

I found a time discrepancy between the risklayer sheet and your data:
- These are the values from [Cases CSV Raw](https://raw.githubusercontent.com/jgehrcke/covid-19-germany-gae/master/cases-rl-crowdsource-by-ags.csv) for 1001 - Flensburg
![image](https://user-images.githubusercontent.com/1193189/107010098-319c1500-6796-11eb-9c51-ac33881251a3.png)
- These are the values from the [risklayer sheet / chronic](https://docs.google.com/spreadsheets/d/1wg-s4_Lz2Stil6spQEYFdZaBEp8nWW26gVyfHqvcl8s/edit#gid=1793926960&range=B21)
![image](https://user-images.githubusercontent.com/1193189/107010337-8049af00-6796-11eb-9991-8a417e5af1ad.png)

You can see it here more clearly:
| Date | Risklayer | Gehrcke |
|-------:|-----------:|----------:|
|03.02.|1123|1093|
|04.02.|1138|1123|
|05.02.|1138|1138|

I actually spotted it in the data of LK Munich but it was easier to show using Flensburg and your raw data. I think this shift is present in the whole dataset.

**Comment by jgehrcke** [comment]
Hello @bdiv! Thanks for the kind words!

A little bit of background: a timestamp with 1 day time resolution, for example `2021-01-16`, is ambiguous: does the corresponding sample reflect the state of the evening of that day, or of the morning of that day? That's an important difference: if it's the morning, then by common sense the sample _actually_ represents the state of the end of the day before.

I have decided to include a timestamp with a time resolution greater than one day so that as the consumer of the data this ambiguity is not present.

In fact, the Risklayer samples must have changed meaning (from morning of the day to evening of the day) at some point in the past; and I didn't notice that. Thank you for reporting this!

I deeply thought about this before; and gladly there is this code comment in [build-rl-csvs.py](https://github.com/jgehrcke/covid-19-germany-gae/blob/18dc01e036edd9195c4fe9462309829e064f3c32/tools/build-rl-csvs.py#L150):

```
        # The risklayer crowd does heavy work in their evening, mapping the result
        # to the _next day_. Example: late in the evening, towards midnight between
        # March 25 and March 26 they settle on the value that they then publish as
        # March 26. That is, set an _early_ hour of the day.
```
The "that they then publish as March 26" is not true anymore. The individual dates in the RL data now represent the state of _the end of the day_. Which makes a little more sense / is more conventional.

I will change corresponding code, and regenerate the data files. Thank you!

**Comment by jgehrcke** [comment]
Update: well, it turns out that the code was fine and the comment was still correct! It's just that in the spreadsheet you took a screenshot of they use the "RKI convention" for showing samples, i.e. they show the EOD state and the date of the corresponding day.

I will now nevertheless change the RL data files, and instead of using an early morning timestamp I will use a late evening timestamp!

For example: `2021-02-08T02:00:00+0000` -> `2021-02-07T22:00:00+0000`

Clarification: when considering the _hour_ this change is practically a noop. When only looking at the _day_ (as you did) then this change might remove confusion, which I totally understand.

**Comment by bdiv** [comment]
Thank you very much for changing this so quickly and the detailed explanation! I'm trying to compare covid19 data sources and know firsthand how hard it is to make those datasets comparable. Thank you again for sharing your work!

**Comment by jgehrcke** [comment]
Thanks for coming back and providing feedback. Much appreciated. With collaboration and interaction, a project like this is a lot more fun.
