### ISSUE TITLE
Set Access-Control-Allow-Origin header for JSON API

### ISSUE THREAD

**Issue by ndeuma** [jgehrcke/covid-19-germany-gae#78]
Without this header, the API is not usable by web applications because of the same origin policy

error message in Chrome, for example:
Access to XMLHttpRequest at 'https://covid19-germany.appspot.com/timeseries/DE-BW/cases' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

See also: https://www.w3.org/wiki/CORS_Enabled#Why_is_CORS_important.3F

**Comment by jgehrcke** [comment]
Hey @ndeuma!

Try sending this header from _your_ server :-)

That is, from the web server behind`'http://localhost:4200'`.

Explanation: when your browser is in the security context of `'http://localhost:4200'` (when this is what's written in the location bar) then JavaScript code running in _that_ security context is by default not allowed to leave that context (to reach out to `https://covid19-germany....`).

_Your_ web server is the authority to make an exception for that, by sending that header.

Makes sense? Unless I have severely misunderstood that... is of course also an option. But that's how I typically solve this :).

For example, when serving https://covid19-germany.appspot.com/static/plots/plot-DEU.html I do set this header in my web server behind gehrcke.de, so that the JavaScript code in that page is allowed to reach out to load external resources.

**Comment by jgehrcke** [comment]
done with https://github.com/jgehrcke/covid-19-germany-gae/pull/80

**Comment by jgehrcke** [comment]
new version is deployed,
```
$ curl -v https://covid19-germany.appspot.com/now 2>&1| grep origin
< access-control-allow-origin: *
```
