### ISSUE TITLE
Landing page: plot new cases

### ISSUE THREAD

**Issue by joaopn** [jgehrcke/covid-19-germany-gae#81]
Very cool repo!

It would be nice to also plot the daily new cases for the comparison plot in the landing page. It would help separate true divergence from reporting delay between sources.

Related: #58

**Comment by jgehrcke** [comment]
Thanks for the kind feedback. You are absolutely right about the relevance of the derivatives here. Will certainly look into that.

**Comment by jgehrcke** [comment]
@joaopn I spent a bit of time on that: https://covid19-germany.appspot.com/

![case-rate-rw-2020-04-10](https://user-images.githubusercontent.com/265630/79041188-0ab09900-7bee-11ea-929f-7588b10b0595.png)

**Comment by jgehrcke** [comment]
This is a hopefully thorough [rate calculation](https://github.com/jgehrcke/covid-19-germany-gae/blob/ef733c35f5f58456b6a93de912cc1e9664280578/tools/plot-compare-sources.py#L85) with a [rolling window analysis](https://github.com/jgehrcke/covid-19-germany-gae/blob/ef733c35f5f58456b6a93de912cc1e9664280578/tools/plot-compare-sources.py#L102), but I'll have to re-check the method and compare numbers to be sure.

**Comment by joaopn** [comment]
Nice comparison! Interesting that even with a pretty large rolling window the sources do not match, due to the heavy weekend effect in the RKI data. It seems likely that JHU logs announcement date (i.e. they scrape what appears in the state press releases, with data that is presumably processed continuously), while RKI logs true testing date, and thus the dip is due to less people getting tested on weekends. We should be able to confirm that with daily number of tests performed, but afaik the RKI only gives weekly numbers.

**Comment by jgehrcke** [comment]
>  the heavy weekend effect in the RKI data

Heavy, yes! That weekend effect alone is a really important observation. The entire world goes crazy with quantitative analysis of case count numbers. In Germany, this weekend effect can be used as a great example to corroborate "hey, these data need be interpreted with great care!" :-).

I think that qualitative statements about the dynamics of the virus spread as well as about the nature of the disease are largely sufficient for estimating risk and for making decisions. But of course for our media that's not convincing enough and they have come up with fancy numbers by doing quantitative analysis which they should better leave to "experts". For example, heute journal (ZDF) plots a "Verdopplungszeit" over time:

![Screenshot from 2020-04-06 01-06-46](https://user-images.githubusercontent.com/265630/79222329-9da03c00-7e57-11ea-8ec1-f0e639db72ce.png)

This is IMO a pretty severe example for over-quantification... I mean, the method in itself is of course super dubious because the concept of the Verdopplungszeit makes most sense in the context of exponential growth. And then of course the weekend effect makes this look even more stupid. And what was most horrifying: the 9.6 (of course, determined to _that_ precision) were "close" to the 10 that Merkel said we should reach many days before (ZDF claimed: we almost reached the goal, only 0.4 left to go!)

In view of the weekend effect I think we should sarcastically apply a Fourier transform to "show" that the virus is actually a religious entity (because  -- clearly  -- it operates with a 7-day periodicity and rests on weekends, RIGHT?) :-).

**Comment by jgehrcke** [comment]
> while RKI logs true testing date, and thus the dip is due to less people getting tested on weekends

It's actually the "Meldedatum" which sadly is not the actual testing date, but the date of the day that a Gesundheitsamt learns about a new case. The test might have been performed days before that. I am also rather sad about that we miss that part of the timeline for each individual case.

**Comment by joaopn** [comment]
By now I'm used to the weekly "spread has slowed down" news every Monday =P
I guess a bit of tea leave reading is to be expected in such a situation.

You are right, the Meldedatum is the reported date. Fortunately, The RKI added a Refdatum field to the query system with what I assume is the self-reported start of symptoms:  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0?selectedAttribute=Refdatum

> Meldedatum: Datum, wann der Fall dem Gesundheitsamt bekannt geworden ist
> Referenzdatum: Erkrankungsdatum bzw. wenn das nicht bekannt ist, das Meldedatum

It paints quite a different picture:

![image](https://user-images.githubusercontent.com/6084685/79236448-3e4d2680-7e6d-11ea-9dad-f05484167759.png)

![image](https://user-images.githubusercontent.com/6084685/79235648-2e811280-7e6c-11ea-81a5-0f4e017932d2.png)

Refdatum (certain) plots only the data where Meldedatum > Refdatum. Unfortunately, we lose about 30% of the entries and 40% of the cases, and the undersampling is very much non-random. So the true start of symptoms timeseries lies somewhere between Refdatum (certain) and Refdatum. 
It is also interesting to consider that in light of the (unfortunately only weekly) number of tests performed: 

![image](https://user-images.githubusercontent.com/6084685/79236465-43aa7100-7e6d-11ea-84f8-b09e376f2400.png)

So one interpretation is that the ramping up in tests after 15/03 managed to catch the earlier unreported cases.

**Comment by jgehrcke** [comment]
@joaopn just some quick meta feedback here: thanks for this exchange of ideas!

I've also had a quick look at the work of your research group and I truly appreciate it. Btw, I am a physicist myself; also had deep contact to MPI-PKS in Dresden during my PhD -- truly appreciate the role of the institute you're working in :-).

**Comment by joaopn** [comment]
@jgehrcke Thanks for the kind words =)
