### ISSUE TITLE
some reason why RKI data is not updated since at 2020-04-08? 

### ISSUE THREAD

**Issue by avila** [jgehrcke/covid-19-germany-gae#93]
it seems that RKI data is not updated since `2020-04-08T17:00:00+0000`. Any reason for that? I havent found an issue on the topic, sorry if I missed it. 
And thanks for the effort, by the way!

**Comment by jgehrcke** [comment]
Hey @avila thanks for asking.

You asked on April 11 and you saw the last data point from April 8.

I updated RKI data today (April 14) and yet the last data point is from April 12.

This is intended and good!

Sometimes the RKI's ArcGIS system doesn't even yield data for the last 1-2 days. When it does then these data points are known to significantly _underestimate_ the actual count.

When one looks at the RKI time series data in their ArcGIS system _today_ then it is reasonable to assume that only the data points up until `today - 2 days` reflect reality reasonably well.

When you want to see case count data then you should categorize your motivation into either i) I want to have a bit of a sensationalistic impression for what the _current_ state is or ii) I want to understand as good as possible what the historical evolution of case count numbers was up until 1-2 days ago.

A bit of a guideline:

- For the "current state" (in whichever way we'd like to define that) it's "best" to look at https://covid19-germany.appspot.com/now (based on most recent data obtained from Gesundheitsaemter by Risklayer, ZEIT ONLINE). This is however a sensationalistic way of looking at things, because a couple of days later you'll find that the RKI data point for what was "now" before is actually more credible, and usually a higher count.

- For looking at the time evolution and spatial evolution of confirmed COVID-19 cases it's best to look at the RKI time series data, but here we simply have to appreciate that the data points of the last couple of days are _significantly_ affected by Meldeverzug.

**Comment by jgehrcke** [comment]
A plot I created on March 31 to visualize this effect:

![data-sources-comparison-2020-03-31](https://user-images.githubusercontent.com/265630/79220627-a6434300-7e54-11ea-93de-2a567965f81b.png)

See how the red line (RKI data is "above" the other lines (other data sources) for most of the past, but not for the most recent days. The decrease of the slope of the red line towards April 1 in that plot is as of processing delays. 

The same plot for today:
![data-sources-comparison-2020-04-14](https://user-images.githubusercontent.com/265630/79220884-22d62180-7e55-11ea-93f7-d7929d3a0d95.png)

Said effect is still there, though a little harder to see as of the scaling properties of the plot.

**Comment by jgehrcke** [comment]
Some quotes from RKI:

> Für die Darstellung der neuübermittelten Fälle pro Tag wird das Meldedatum verwendet – das Datum, an dem das lokale Gesundheitsamt Kenntnis über den Fall erlangt und ihn elektronisch erfasst hat. 

> Zwischen der Meldung durch die Ärzte und Labore an das Gesundheitsamt und der Übermittlung der Fälle an die zuständigen Landesbehörden und das RKI können einige Tage vergehen (Melde- und Übermittlungsverzug). Jeden Tag werden dem RKI neue Fälle übermittelt, die am gleichen Tag oder bereits an früheren Tagen an das Gesundheitsamt gemeldet worden sind. Diese Fälle werden in der Grafik Neue COVID-19-Fälle/Tag dann bei dem jeweiligen Datum ergänzt. 

> Durch den Meldeverzug sind die Daten die letzten Tage in der Grafik  noch unvollständig und füllen sich mit den in den kommenden Tagen nachfolgend übermittelten Daten auf.  Aus dem Verlauf der übermittelten Daten allein lässt sich daher kein Trend zu den aktuell erfolgten Neuinfektionen ablesen.

**Comment by avila** [comment]
wow! thanks for the great response (ant the work!). 
I believe I can close this issue very well closed! :)
